### ISSUE TITLE
"Automatische ID" beim Anlegen eines neuen Users ist schon vergeben, wird nicht passend hochgezählt

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#104]

**Comment by jzakotnik** [comment]
Wie kann man das reproduzieren? Aktuell wird von allen IDs das Maximum genommen und +1 hinzugezählt

**Comment by fb4thxUall** [comment]
Bei mir fehlt immer genau das +1 Hochzählen, bei mir steht da die maximale ID drin... (nachdem ich zuvor eine selbst gewählte ID vergeben habe und anschließend eine automatische haben wollte). Ich checke das später nochmal.

**Comment by fb4thxUall** [comment]
Ich konnte das jetzt nicht mehr reproduzieren. Habe aber einen Verdacht: Das war, nachdem ich eine zu große Zahl als ID eingegeben hatte (BigInt Story), das abgeschmiert ist und ich dann später den DB-Eintrag händisch gelöscht hatte, danach war dann der Fehler. Betrachten wir es als erledigt.
