### ISSUE TITLE
Dringend: Die Bücher-Etiketten beinhalten nicht den Barcode

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#106]
Es ist essentiell, dass man Barcode-Etiketten für die Bücher drucken kann.

**Comment by jzakotnik** [comment]
Das ist eigentlich leicht implementierbar, es schien in der aktuellen Nutzung nicht mehr so praktisch, weil die Buchsuche so gut funktioniert hat (via ID oder Titel, oder oder), dass es schneller ging als mit einer Laserpistole zu hantieren.

**Comment by jzakotnik** [comment]
Kämpfe gerade noch mit https://react-pdf.org/styling aber wird noch 👍

**Comment by jzakotnik** [comment]
Jetzt braucht es noch ein wenig styling - was sind ungefähr die Abmessungen vom QR Code und was soll außerdem noch drauf?
<img width="306" alt="image" src="https://github.com/jzakotnik/openlibry/assets/551599/8800bd8d-c818-4d53-a023-58bf7828312b">

**Comment by fb4thxUall** [comment]
Ich kann kaum beurteilen, wie es für die Allgemeinheit am besten ist. Ich beschreibe jetzt einfach mal unseren Use-Case, vielleicht trifft er ja auf viele zu:

Wir sortieren die Bücher in den Regalen zuerst nach Genre. Innerhalb eines Genres dann nach Autor, damit man im Regal nicht ewig suchen muss, sondern anhand der alphabetischen Sortierung des Autorennamens schneller zum Ziel kommt. Deswegen würden wir gerne die Label auf auf das Buch kleben, dass auf dem Buchrücken der Autorenname lesbar ist. Alles andere muss nicht auf dem Buchrücken lesbar sein.
Diese Sortierweise haben auch sehr viele Bibliotheken, sodass das vermutlich allgemein vielen hilft.

Sonst noch drauf abgesehen vom Barcode sollte das Genre (da nehmen wir, da nicht anders verfügbar, die Kategorie "Sonstiges". Das wiederum passt ja auch für andere, falls man alternativ den Sponsor drauf haben möchte.). 

Zum Styling: Da es für die Allgemeinheit (und deinen Aufwand) eventuell doof sein könnte, den Autorennamen vertikal zu drucken, schlage ich folgenden Workaround vor: Der Autorenname muss weiter links als der Barcode starten, damit man den Anfangsbuchstaben des Autoren-Nachnamens auf den Buchrücken kleben kann, der Rest geht dann "um die Ecke" aufs Cover. Der Barcode darf aber für den Scanner nicht um die Ecke geklebt sein. Deswegen der Versatz.
Falls das nicht geht und alles linksbündig starten muss, würden wir es trotzdem so kleben und einfach ein zweites Label für den Barcode nochmal ins Buch rein kleben. 


Vorschlag für "Eigentum der Schulbücherei": Da könnte auch stehen "Eigentum von:  + <Name der in der .env hinterlegten Organisation>" 

Zuletzt zum Gesamtstyling des DIN A4 Blattes: Man könnte entweder darauf setzen, dass man als selbstklebende Etiketten ein Gesamtblatt bedruckt und das dann selbst zerschneidet. Das wäre natürlich recht aufwendig bei vielen Büchern (wir haben 5000).
Komfortabler wäre es, auf ein Standard-Format von Etiketten anzupassen. Da gibt es für mich zwei Größen, die mir auf den ersten Blick sinnvoll erscheinen: 8 pro Seite oder 10 pro Seite:

97x67,7mm auf A4 (8 Pro Seite) https://www.amazon.de/AVERY-Zweckform-3426-Universal-Etiketten-Etiketten/dp/B000WKZPHG?sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY
97x55mm auf A4 (10 Pro Seite)
105 x 57 mm auf A4 (10 Pro Seite) https://www.amazon.de/Blatt-Aufkleber-Etiketten-Selbstklebend-matt/dp/B07NTXZX5R





Zusammenfassung:
Barcode + gedruckte BuchID
Autorname (muss weiter links als der Barcode starten)
Genre/Sonstiges

**Comment by jzakotnik** [comment]
Der Autorenname kommt noch, aber vom Format müsste es theoretisch auf die Etiketten passen von Avery:
[Testlalbels.pdf](https://github.com/user-attachments/files/16168888/Testlalbels.pdf)

**Comment by fb4thxUall** [comment]
Das sieht ja schon sehr vielversprechend aus. Ich vermute, die Formatierung war ziemlich zeitaufwendig. Aber wenn das funktioniert, wird das auch extrem viele Stunden eingespart haben. 

Ich habe mir gerade mal ein Paket von den Etiketten bestellt, es kommt Montag an. Dann teste ich es direkt mal zu drucken.

**Comment by jzakotnik** [comment]
@fb4thxUall so traurig das auch ist, aber das layout war überhaupt nicht aufwändig, es gab nur zu viele Sommerfeste + Fussball 🥇 . 

Die Verteilung der Barcodes ist [hier ](https://github.com/jzakotnik/openlibry/blob/9d764d8a6083d30803bddc849eca7ad9d9c923d4/pages/api/report/booklabels/index.tsx#L71)codiert, das kann man noch leicht tweaken wenn es nicht exakt auf die Aufkleber passt:

**Comment by jzakotnik** [comment]
So irgendwie?
<img width="289" alt="image" src="https://github.com/user-attachments/assets/e84e7ec2-68b1-4e44-9660-d57092ddc818">

**Comment by fb4thxUall** [comment]
Ja, ziemlich gut. Ich würde noch etwas mehr Abstand zwischen Autor und Rest vorschlagen, damit es nicht so eng an der Knickkante ist, vor allem bei Hardcover Büchern. Mega



Am 12. Juli 2024 15:27:23 MESZ schrieb Jure Zakotnik ***@***.***>:
>So irgendwie?
><img width="289" alt="image" src="https://github.com/user-attachments/assets/e84e7ec2-68b1-4e44-9660-d57092ddc818">
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/106#issuecomment-2225590925
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
I try. React-PDF und ich stehen grad etwas auf Kriegsfuss 😸

**Comment by jzakotnik** [comment]
So, nächste Version.. der Autorenname wird allerdings bei x Buchstaben (aktuell 15) abgekürzt, sonst gehts über das Etikett hinaus?
Falls es ungefähr so passt, dann könnte ich die Abmessungen leicht in die `.env` Variablen packen
[book_update.pdf](https://github.com/user-attachments/files/16198142/book_update.pdf)

**Comment by fb4thxUall** [comment]
Ah, das in die .env zu packen ist eine sehr gute Idee. Mein Vorschlag wäre, dass wir mal meine Testdrucke Anfang der Woche abwarten und schauen, was sich da ergibt. Ansonsten sieht es für mich ziemlich gut aus. 



Am 12. Juli 2024 20:46:11 MESZ schrieb Jure Zakotnik ***@***.***>:
>So, nächste Version.. der Autorenname wird allerdings bei x Buchstaben (aktuell 15) abgekürzt, sonst gehts über das Etikett hinaus?
>Falls es ungefähr so passt, dann könnte ich die Abmessungen leicht in die `.env` Variablen packen
>[book_update.pdf](https://github.com/user-attachments/files/16198142/book_update.pdf)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/106#issuecomment-2226174758
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Ein Test-Scan wäre noch gut, scheinbar gibt es auch verschiedene Barcode Standards.

**Comment by jzakotnik** [comment]
Im `.env` file gibt es jetzt ein paar Variablen um das zu konfigurieren:

```
BOOKLABEL_LOGO=schullogo_buchlabel.png
BOOKLABEL_MARGIN_LEFT = 1
BOOKLABEL_MARGIN_TOP = 2
BOOKLABEL_SPACING = 5.5
BOOKLABEL_ROWSONPAGE = 5
BOOKLABEL_COLUMNSONPAGE = 2
BOOKLABEL_BARCODE_WIDTH = "3cm"
BOOKLABEL_BARCODE_HEIGHT = "1.6cm"
BOOKLABEL_BARCODE_VERSION = "code128"
BOOKLABEL_BARCODE_PLACEHOLDER = "barcode"
```

Bei `barcode` wird der barcode gerendert, bei allem anderen (z.B. `logo` wird stattdessen das Schul-Logo genommen und die Zahl darunter gerendert).

**Comment by fb4thxUall** [comment]
De Etiketten sind gerade angekommen. Es passt tatsächlich nicht ganz. Die Höhe sitzt jeweils perfekt. Aber die zweite Spalte fängt zu weit links an. Anbei mal ein Scan, damit du das mal sehen kannst.

Da noch massig Platz ist auf dem Etikett: Zwischen Autor und Barcode ist sehr wenig Platz, ich bekomme es ganz gerade eben so um die Buchecke. Ich würde da noch ein bis zwei cm mehr Abstand spendieren, vielleicht auch als Variable, muss aber nicht für mich als Variable.

Bei Bedarf könnte man vom Platz noch ne weitere Info dazu packen wie z.B. "Sonstiges".

Das "Eigentum der Schulbücherei" könnte auch ein Text aus der .env sein.


Zum Barcode an sich: Er wird korrekt gelesen, sehr cool.

**Comment by jzakotnik** [comment]
Super, das bekommen wir bestimmt hin, hab auch nicht erwartet, dass es zufällig beim ersten Mal passt ;-). Ich kann mir ja ein A4 Blatt ausdrucken, wo die Etiketten aufgemalt sind, dann kann man testen wohin gedruckt wird. Auf dem Scan sieht man es nicht so gut, wo sind die Aufkleber zu Ende? Da wo die Pfeile sind?

**Comment by jzakotnik** [comment]
Hab [diese Word Vorlage](https://www.avery-zweckform.com/vorlage-3679) gefunden bei Avery, waren das die Etiketten?

**Comment by fb4thxUall** [comment]
Du kannst im pdf ranzoomen und dann kann man sie gut erkennen. Hab ich beim Scan extra drauf geachtet. 
Bin leider heute unterwegs und hab keinen richtigen Zugriff auf die Sachen gerade, sorry. 

Es waren von Avery die Etiketten aus dem Link mit 10 pro Blatt. 

LG

Am 14. Juli 2024 10:50:51 MESZ schrieb Jure Zakotnik ***@***.***>:
>Super, das bekommen wir bestimmt hin, hab auch nicht erwartet, dass es zufällig beim ersten Mal passt ;-). Ich kann mir ja ein A4 Blatt ausdrucken, wo die Etiketten aufgemalt sind, dann kann man testen wohin gedruckt wird. Auf dem Scan sieht man es nicht so gut, wo sind die Aufkleber zu Ende? Da wo die Pfeile sind?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/106#issuecomment-2227270061
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fb4thxUall** [comment]
Ja, da müsstest du die richtige Vorlage haben rein von den Zahlen her. Kann es wie gesagt gerade nicht testen.


Am 14. Juli 2024 10:53:28 MESZ schrieb Jure Zakotnik ***@***.***>:
>Hab [diese Word Vorlage](https://www.avery-zweckform.com/vorlage-3679) gefunden bei Avery, waren das die Etiketten?
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/106#issuecomment-2227270639
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Ah perfekt, es war mir nicht klar, dass die Linien die Ränder der Aufkleber sind.. dann versuche ich das mal zurecht zu zuppeln und konfigurierbar zu machen.

Bei der Word Vorlage ist mir eh als Plan B aufgefallen, dass man auch ein beliebiges Word designen könnte und dann an Platzhaltern definieren könnte wo Barcode, Autor, Titel, etc rein kommen. Vielleicht eine gute Idee für die Zukunft.

**Comment by jzakotnik** [comment]
Wenn ich es richtig überblicke sieht’s jetzt besser aus. Nur den Abstand zwischen Autor und Titel muss ich noch ins env file tun 
![IMG_5150](https://github.com/user-attachments/assets/5c540c29-30a1-42a6-a6c7-ff17d6efa878)

**Comment by fb4thxUall** [comment]
Super nice, es passt alles. Ich schließe damit mal dieses Issue.
