### ISSUE TITLE
Die Bücher-Etiketten sollten neben Barcode und Titel auch den Autoren beinhalten, ...

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#107]
... damit Bücher anhand der Etiketten innerhalb eines Genres im Regal nach Autor sortiert werden können. Auch wäre gut, wenn auch das Genre mit drauf stünde, allerdings macht das notwendig, dass das Genre überhaupt erfasst werden kann.

**Comment by jzakotnik** [comment]
Die Idee ist interessant, bei einer anderen Schule wollte man noch gerne den Spender drauf haben.
Ist es nicht sinnhafter QR Codes zu haben? Gefühlt sind die Laserpistolen auf dem absteigenden Ast, besonders weil man mit Handys/iPads leichter QR Codes einscannen kann.

**Comment by fb4thxUall** [comment]
Den Gedanken mit dem QR-Code hatte ich auch schonmal, aber...

Barcode-Scanner sind oft schon vorhanden. Außerdem sind die relevanten Geräte in einer Schulbib oft ein Laptop/PC an der Theke der Bib und die SuS kommen mit dem Buch zur Theke. Dann wird es für den PC eingescannt. 

Und weiter wäre ein QR-Code für nur eine Zahlenfolge eher Overkill. Will man alle Infos da reinpacken, wäre der natürlich wieder super. Das allerdings ist nicht relevant, um an der Theke eingescannt zu werden. Dort will man ja nur nicht die Buch-ID abtippen. Das ist auch software-technisch deutlich kompatibler, weil die Barcode-Scanner wie eine Tastatur funktioniert und das Einscannen dadurch reibungslos in jeder Software klappt.


Mein Plädoyer: Barcode höchste Prio, QR Code als optionale Ergänzung, wenn man mal "Langeweile" hat.

**Comment by fb4thxUall** [comment]
Im anderen Issue mit erledigt.
