### ISSUE TITLE
Dringend: Import Error

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#122]
Im Log ist kein weiterer Error vermerkt, deswegen nur diese Problembeschreibung vom Bild.

![Import Error](https://github.com/user-attachments/assets/84f0215c-268a-47cb-9c4d-82617e27e79f)

Die verursachende Datei habe ich ebenfalls mal angehängt.
[openlibry_import.xlsx](https://github.com/user-attachments/files/16322249/openlibry_import.xlsx)

**Comment by jzakotnik** [comment]
Danke, das schaue ich mir an. Übrigens noch ein Tipp, man kann die Userdaten relativ leicht mit diesem curl-Befehl anonymisieren. Für Testing nicht schlecht.. 
`curl http://localhost:3000/api/openbiblioimport/anonymiseUsers`

**Comment by jzakotnik** [comment]
In dem angehängten Excel sind in der Userliste keine User - sollten da nicht 3 sein (wenn ich den Screenshot richtig deute) ?

**Comment by fb4thxUall** [comment]
Hm... Also ich wollte nur Bücher importieren und die Userliste sollte leer sein. Hab ich was am Excel Dokument vergeigt?

Am 21. Juli 2024 10:06:37 MESZ schrieb Jure Zakotnik ***@***.***>:
>In dem angehängten Excel sind in der Userliste keine User - sollten da nicht 3 sein (wenn ich den Screenshot richtig deute) ?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/122#issuecomment-2241519426
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Ah, guter Use Case, das habe ich noch nicht ausprobiert. Hatte als Test nur exportiert und dann importiert, sozusagen als Backup für die normalen User. Finde aber auch dass es funktionieren sollte.

**Comment by jzakotnik** [comment]
Hast Du mit einer leeren Datenbank angefangen?

**Comment by fb4thxUall** [comment]
Ja

Am 21. Juli 2024 19:03:45 MESZ schrieb Jure Zakotnik ***@***.***>:
>Hast Du mit einer leeren Datenbank angefangen?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/122#issuecomment-2241713887
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Ja, da sind verschiedene Fehler, arbeite mich noch durch..
- Scheinbar denkt der Importer, da sind 1 Million Zeilen. Habe alle leeren Zeilen gelöscht, danach ging e
- Beim User das gleiche, die 3 leeren Zeilen gelöscht
- Dann das Problem, dass die "Seitenzahl" als `string` im Excel ist, das ist im Importer jetzt abgefangen und als Zahl konvertiert
- Scheint aber noch ein Problem nach dem Import zu geben, das schau ich mir grad an..

**Comment by jzakotnik** [comment]
Problem gefixt, dass Import abgestürzt war, falls keine Schlagwörter im Excel waren

**Comment by jzakotnik** [comment]
[openlibry_import.xlsx](https://github.com/user-attachments/files/16326022/openlibry_import.xlsx)
Mit diesem Excel geht es (als Beispiel) erstmal..

**Comment by jzakotnik** [comment]
Leere Zeilen im Excel werden jetzt ignoritert, insofern müsste es auch mit dem originalen Excel gehen

**Comment by fb4thxUall** [comment]
Top, funktioniert jetzt alles reibungslos. Vielen Dank
