### ISSUE TITLE
Lange Ladezeiten

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#126]
Seit einigen Updates, hab leider den Überblick verloren, ist OpenLibry zumindest gefühlt (deutlich) langsamer als vorher. Die Ladezeiten der einzelnen Seiten ist erstaunlich hoch. Egal welche Seite. Ich finde aber im Moment keine Ursache. Es kann nicht an der Menge der Bücher liegen, denn es ist bei jeder Seite so. Auch dann, wenn noch gar kein Buch/User etc. in der DB enthalten sind. 

Ist kein Beinbruch und es funktioniert soweit im Moment erstmal alles. Ich dachte mir aber, ich melde es trotzdem mal zurück.

LG

**Comment by jzakotnik** [comment]
So, zurück aus dem Urlaub :-)
Das ist wirklich seltsam, ist es nur beim initialen Laden der Seite oder wenn man später was tut?

**Comment by fb4thxUall** [comment]
Ne, immer. Aber kannst du es denn überhaupt reproduzieren bzw. nachempfinden? Ich mache in Kürze die finale Installation, dann schaue ich nochmal genauer, ob ich was finde.

War selbst in der Zwischenzeit weg, hoffe es war schön.

LG

Am 11. August 2024 13:24:00 MESZ schrieb Jure Zakotnik ***@***.***>:
>So, zurück aus dem Urlaub :-)
>Das ist wirklich seltsam, ist es nur beim initialen Laden der Seite oder wenn man später was tut?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/126#issuecomment-2282724950
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Es gibt definitiv noch Dinge, die man an der Performance verbessern kann, es war bisher nur nicht nötig. 

Gut wäre es zu wissen, ob das Bottleneck der Server ist (beim Laden der Seite werden die Daten einmal in den Browser geladen, damit man z.B. dann schneller suchen kann) oder im Browser (z.B. wenn die Suche ausgeführt wird). Das sieht man in den Developer Tools bei den Ladezeiten:

![image](https://github.com/user-attachments/assets/ae3298be-9c69-4803-bdb8-ad7f21e3ee63)

**Comment by fb4thxUall** [comment]
Hat sich zunächst wieder erledigt mit den sonstigen Bugfixes.
