### ISSUE TITLE
Dringend: Installation schlägt plötzlich fehl

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#127]
Hallo zusammen,

nach den ganzen Tests mache ich gerade die finale Installation für das Produktivsystem und  da gibt es plötzlich einen Fehler, den es vorher nie gab. Hab es schon in diversen Versionen gegoogled, habe es mehrfach von neu wiederholt usw., ich finde das Problem einfach nicht. Habe auch alte Versionen von OpenLibry getestet, ist da aber genauso, obwohl es damals ging. 

Vielleicht hat jemand einen Hinweis, wo zu suchen ist?

![Installationsfehler](https://github.com/user-attachments/assets/55e728ef-e1c6-4dda-93b5-bcb0dc288d77)

Danke schon im Vorraus.

Liebe Grüße

**Comment by fb4thxUall** [comment]
Es scheint was mit npm bzw. falschen Abhängigkeiten zu tun zu haben in package.json und package-lock.json

https://sylhare.github.io/2022/02/09/How-to-fix-npm-dependency-library-hell.html

Aber bin noch nicht wirklich weiter.

**Comment by fb4thxUall** [comment]
Möglicherweise bin ich bisher auf einem total falschen Weg. Es scheint mir langsam so auszusehen, als wäre die .env falsch und würde in Kombination mit Prisma diesen Fehler verursachen. Allerdings liegt es nicht an meiner individuellen Konfiguration, wenn ich es mit der (umbenannten) .env-example mache, ist es genauso. Leider ist die Fehlermeldung nicht so aussagekräftig, sodass ich gerade nicht weiterkomme.

**Comment by jzakotnik** [comment]
Ich versuche es gerade mal nachzuvollziehen...

**Comment by jzakotnik** [comment]
Kannst Du es nochmal versuchen? Ich habe einmal den `node_modules` Folder gelöscht (der wird eh neu aufgebaut) und die Reihenfolge im `Dockerfile` verändert. Vermutlich war irgendwo eine alte Bibliothek drin.

**Comment by fb4thxUall** [comment]
Habs von cleaner Neuinstallation aus gemacht und wieder gleicher Fehler. Ich hatte es vorhin auch schonmal mit einer alten Version von openlibry versucht, die damals definitiv funktionierte. Auch hier gleicher Fehler. Es sieht also irgendwie so aus, als hätten sich durch irgendwelche Updates etc. die Probleme ergeben. Ich suche selber weiter mit, aber aktuell stehe ich nach wie vor ziemlich auf dem Schlauch.

**Comment by jzakotnik** [comment]
Das aktuelle Dockerfile hast Du gepullt oder? Damit hatte es bei mir funktioniert, kann es nochmal von scratch versuchen..

**Comment by fb4thxUall** [comment]
Hatte komplett neu runtergeladen, aber ich schau mal gerade nach, ob das auch richtig war

**Comment by fb4thxUall** [comment]
Jap, war das neue, daran lag es nicht. 

Ich hab zwei Wege versucht. Einmal die komplette Installation "Bare Metal auf Raspi", da bekommt man keine Fehler während der Installation und kann anschließend openlibry im Browser aufrufen. Allerdings kann ich da nur die Startseite ansehen, sobald ich auf z.B. User gehe, kommt ein Fehler, der u.a. vorschlägt, "prisma generate" auszuführen (das ist genau der Befehl, der im Dockerbuild failed).

Wenn ich im anderen Versuch direkt für Docker bauen will, dann kommt der Fehler wie oben im Foto.

**Comment by fb4thxUall** [comment]
![Installationsfehler2](https://github.com/user-attachments/assets/a17461e2-5d81-491e-8c4f-092d0e861b94)

So sieht das aus.

**Comment by jzakotnik** [comment]
Das ist wirklich seltsam, habe folgendes ausprobiert, da ging es:

- Fresh git clone in einen neuen temp folder
- Copy vom aktuellen `.env` file in den folder
- `docker build --no-cache -t openlibry .  ` ausgeführt
- `docker run -i -p 3000:3000 -t openlibry `

Klappt das bei Dir?

**Comment by fb4thxUall** [comment]
Hm, das lief problemlos und scheint auch im Betrieb zu klappen. 

Die letzte Zeile heißt allerdings: 
`docker run -i -p 3000:3000 -t openlibry -openlibry`

Hattest du denn nochmal was geändert am Repo? Ich verstehe nämlich nicht, was der relevante Unterschied ist zu vorher. Ich habe jetzt vorher die "Plain"-Installation nicht gemacht und von der cleanen Installation aus direkt nur deinen Teil, da ging es jetzt, obwohl ich sagen würde, ist ja identisch zu vorher...

**Comment by fb4thxUall** [comment]
Falls du nichts mehr geändert haben solltest, sollten wir in die Installationsanleitung evtl den Hinweis aufnehmen, dass man nicht erst das eine und dann das andere machen sollte. Da scheint sich ja sonst was in die Quere zu kommen. Allerdings bin ich mir sehr sicher, dass das "früher" auch problemlos ging. Ich hab es mal so und mal so getestet, und eigentlich ging die Installation immer.

So oder so danke ich dir sehr für deinen Support. (Mal wieder)

Ich habe heute ungeplant einige Stunden da rein gesteckt und das wären alleine noch einige mehr geworden.

**Comment by jzakotnik** [comment]
@fb4thxUall Sorry für den Zeitaufwand, bin auch noch so der `docker` Experte und in Kombination mit Prisma ist es irgendwie ein Mysterium. Aber wir kriegen es bestimmt raus 🥇

**Comment by fb4thxUall** [comment]
Zu früh gefreut. Es war zunächst alles aufrufbar, dann habe ich den Buchbestand importiert. Hat auch geklappt. Seitdem sind aber (auch nach Neustart nicht) die einzelnen Bücher nicht mehr aufrufbar und die Reports-Seite gar nicht. Irgendwas ist auf dem Weg auf der Strecke geblieben. Das funktionierte bisher ja problemlos. 

Muss aber nicht mehr heute funktionieren :-D

**Comment by fb4thxUall** [comment]
Ich schau hier auch selbst erstnochmal genauer, gib dir noch keine Mühe

**Comment by fb4thxUall** [comment]
Ich mache ein separates Issue auf dafür, habe zumindest den ersten Fehler gefunden.

**Comment by fb4thxUall** [comment]
Das erste Problem, dass die Bücher nicht mehr einzeln angezeigt wurden, ist gelöst mit dem Coverimage (siehe separates Issue). Das zweite Problem, dass man nach Import des Datenbestands die Report-Seite nicht mehr laden kann, hat eine Ursache mit einer fehlenden Datei im Kontext Antolin:

 
![Fehler3](https://github.com/user-attachments/assets/0ef2a578-af72-4b1c-8d1d-eb03b22414c2)

**Comment by fb4thxUall** [comment]
Die Installation an sich scheint jetzt (mit Docker, Plain nicht mehr getestet) wieder zu funktionieren. Deswegen schließe ich das hier.
