### ISSUE TITLE
Report nicht mehr aufrufbar

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#129]
Nach dem Import eines Bestandes...

![Fehler3](https://github.com/user-attachments/assets/0aba11e5-2dfe-40ab-a0f3-59b0acc68c23)

**Comment by jzakotnik** [comment]
Da baue ich Fehlderhandling ein. Ich glaube der Antolin Verlag wollte nicht, dass man das csv File einfach verteilt, sondern wollten lieber gefragt werden. Sonst könnte es Teil vom Repo sein.

**Comment by jzakotnik** [comment]
Error handling eingefügt, sollte jetzt auch ohne Antolin File gehen. Good catch, danke!

**Comment by jzakotnik** [comment]
Versuche das gerade nachzuvollziehen, wann passiert der Fehler? Wenn man ein Buch anklickt?

**Comment by fb4thxUall** [comment]
Wenn man die Report Seite aufruft, nachdem man was importiert hat.

Am 17. August 2024 15:00:04 MESZ schrieb Jure Zakotnik ***@***.***>:
>Reopened #129.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/129#event-13919803539
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fb4thxUall** [comment]
Wenn man die Report Seite aufruft, nachdem man was importiert hat.

Am 17. August 2024 15:01:45 MESZ schrieb Jure Zakotnik ***@***.***>:
>Versuche das gerade nachzuvollziehen, wann passiert der Fehler? Wenn man ein Buch anklickt? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/129#issuecomment-2294853504
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fb4thxUall** [comment]
Ich merke, du bastelst gerade. Vielleicht nervt es, vielleicht nicht. Hier ein aktueller Zwischenstand zum aktuellen Stand des Repos:

![Uploading Installationsfehler4.png…]()

**Comment by jzakotnik** [comment]
Oh nein das war mein Fehler. Der macht erst das Prisma Kommando bevor das env file da ist… das Copy . . muss wieder rauf wie vorher . Bin noch unterwegs leider

**Comment by fb4thxUall** [comment]
Alles gut, kein Stress.

**Comment by fb4thxUall** [comment]
Omg nein, das war meine Blödheit. Entschuldigung, ich hoffe du hattest noch keine weitere Zeit in meinen letzten Post investiert, denn es funktioniert wohl. Ich hab versehentlich ein Leerzeichen in den Dateinamen von .env eingebaut. 😔 

Am 17. August 2024 20:16:42 MESZ schrieb Jure Zakotnik ***@***.***>:
>Oh nein das war mein Fehler. Der macht erst das Prisma Kommando bevor das env file da ist… das Copy . . muss wieder rauf wie vorher . Bin noch unterwegs leider 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/129#issuecomment-2294933234
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fb4thxUall** [comment]
Ich checke es gleich nochmal in Ruhe und melde mich dann nochmal. 

Am 18. August 2024 07:05:18 MESZ schrieb Fabian Blasius ***@***.***>:
>Omg nein, das war meine Blödheit. Entschuldigung, ich hoffe du hattest noch keine weitere Zeit in meinen letzten Post investiert, denn es funktioniert wohl. Ich hab versehentlich ein Leerzeichen in den Dateinamen von .env eingebaut. 😔 
>
>Am 17. August 2024 20:16:42 MESZ schrieb Jure Zakotnik ***@***.***>:
>>Oh nein das war mein Fehler. Der macht erst das Prisma Kommando bevor das env file da ist… das Copy . . muss wieder rauf wie vorher . Bin noch unterwegs leider 
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/jzakotnik/openlibry/issues/129#issuecomment-2294933234
>>You are receiving this because you authored the thread.
>>
>>Message ID: ***@***.***>
>-- 
>Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fb4thxUall** [comment]
So, also das Docker build funktioniert wohl, da war ich zu doof, sorry.

Aber der eigentliche Fehler, dass die Report Seite nach dem Import nicht mehr aufrufbar ist, besteht weiterhin. Allerdings ist die Fehlermeldung dazu jetzt weg. Es kommt gar kein Hinweis mehr auf einen Fehler in der Dockerkonsole. Im Browser steht auch nichts mehr hilfreiches. 




Am 18. August 2024 07:14:00 MESZ schrieb Fabian Blasius ***@***.***>:
>Ich checke es gleich nochmal in Ruhe und melde mich dann nochmal. 
>
>Am 18. August 2024 07:05:18 MESZ schrieb Fabian Blasius ***@***.***>:
>>Omg nein, das war meine Blödheit. Entschuldigung, ich hoffe du hattest noch keine weitere Zeit in meinen letzten Post investiert, denn es funktioniert wohl. Ich hab versehentlich ein Leerzeichen in den Dateinamen von .env eingebaut. 😔 
>>
>>Am 17. August 2024 20:16:42 MESZ schrieb Jure Zakotnik ***@***.***>:
>>>Oh nein das war mein Fehler. Der macht erst das Prisma Kommando bevor das env file da ist… das Copy . . muss wieder rauf wie vorher . Bin noch unterwegs leider 
>>>
>>>-- 
>>>Reply to this email directly or view it on GitHub:
>>>https://github.com/jzakotnik/openlibry/issues/129#issuecomment-2294933234
>>>You are receiving this because you authored the thread.
>>>
>>>Message ID: ***@***.***>
>>-- 
>>Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
>-- 
>Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Habe in der aktuellen Version ein paar Log messages für den Server (docker) eingefügt, wenn die Reports Seite geöffnet wird. Sieht man da was?

**Comment by fb4thxUall** [comment]
Fehler bleibt. Man sieht nichts. Das bringt mich zu dem Gedanken, dass der Import-Vorgang gar nicht zu Ende geführt wird (was bis kürzlich aber ja problemlos ging.) 
Die Fehlermeldung der Webseite sagt nur, "schau mal in die Browser-Konsole". Da sehe ich nur folgendes, woraus ich nicht so wirklich schlau werde.

In der Dockerkonsole sehe ich nichts, da scheint irgendwie der Import noch zu laufen, es wird aber einfach nichts mehr gedruckt.

![Fehler5](https://github.com/user-attachments/assets/5e656b5e-6fcc-4611-b831-e59f33692427)

**Comment by jzakotnik** [comment]
Hmm, da scheint es ein Problem mit den Schlagwörtern zu geben - ist im Excel da irgendwas seltsames zu sehen? Oder nur Leerzeichen oder ähnliches?

**Comment by jzakotnik** [comment]
Ah, ich denke das Problem ist, dass es keine Schlagwörter im Excel gibt und bei der Reports Page wird eine Word-Cloud dargestellt, das kann ich fixen.
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/b40359ea-f64f-4405-a6f3-dd059fc9b23d">

**Comment by fb4thxUall** [comment]
Ah, ja manche wenige Bücher sind ohne Schlagwörter. 

Hier ist nochmal die Datei, mit der ich immer teste. Die ist aber seit jeher unverändert.
[openlibry_import.xlsx](https://github.com/user-attachments/files/16647768/openlibry_import.xlsx)

**Comment by jzakotnik** [comment]
Danke, damit kann ich den Fehler nachvollziehen, das ist leicht fixbar. Ich war bei den Schlagwörtern davon ausgegangen, dass sie mit ";" getrennt sind.

**Comment by jzakotnik** [comment]
Hab es gefixt, der Fehler war mit Deiner Datei auch da und jetzt weg.. danke!!

**Comment by fb4thxUall** [comment]
Wohoo, läuft alles. Ich danke dir sehr. Erweiterte Anleitung ist auch quasi fertig. Kommt evtl heute Abend oder Anfang der Woche.
