### ISSUE TITLE
Docker compose zickt

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#131]
Kein wirkliches Problem, aber in der aktuellen Version tritt der Fehler, dass die Report-Seite nach dem Import von Büchern nicht mehr aufrufbar ist (Problem mit den Leeren Schlagwörtern) auf, wenn ich den Container mit docker compose up starte. Mache ich es über den manuellen run Befehl, funktioniert alles. Ich habe es mehrmals probiert, es erschließt sich mir nicht im geringsten und es ist auch kein wirkliches Problem, weil es ja den mauellen Start gibt. Aber ich wollte es erwähnen.

Jedenfalls habe ich die neue Anleitung entsprechend ohne docker compose formuliert.

PS: Produktive Installation läuft, wird die Tage vom Team in Benutzung genommen.

**Comment by jzakotnik** [comment]
Das ist wirklich seltsam, hatte den Import so abgeändert, dass bei einer leeren Excel Zelle trotzdem die Schlagwörter auf einen leeren String gesetzt werden. Welcher Fehler kommt dann beim Start?
Bei dem `docker-compose` wird die DB auf ein volume gemappt, so dass sie nicht verloren geht. Das hast Du bei dem normalen Docker auch?

**Comment by jzakotnik** [comment]
Hast Du vor dem Neustart das gemountete Volume bzw. das DB File gelöscht? Default-mässig ist es hier `./database:/app/prisma/database`. Kann sein, dass der Import mit der alten Version dann noch den Fehler drin hat..

Ich teste das auch nochmal mit dem Testfile.

**Comment by fb4thxUall** [comment]
Das hatte ich auch im Verdacht und habe dann getestet, den Pfad in der yml zu ändern bzw. Weg zu nehmen, damit es identisch ist zum manuellen run. Aber das änderte nichts. Ich kann es mir eigentlich nur mit einem Bedienungsfehler durch mich erklären, aber gerade deswegen habe ich es zug mal probiert und in verschiedenen Versionen. Ich stehe da wirklich auf dem Schlauch.

Ich schaue die Tage nochmal drauf.

Am 19. August 2024 22:58:24 MESZ schrieb Jure Zakotnik ***@***.***>:
>Hast Du vor dem Neustart das gemountete Volume bzw. das DB File gelöscht? Default-mässig ist es hier `./database:/app/prisma/database`. Kann sein, dass der Import mit der alten Version dann noch den Fehler drin hat..
>
>Ich teste das auch nochmal mit dem Testfile.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/131#issuecomment-2297444275
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Ich kann den Fehler reproduzieren und denke kann es auch leicht lösen. Bei mir scheint es nur unter Docker so, als ob nach dem Import auf der Bücherseite der Browser versucht die Cover zu laden, diese sind nicht da und dann bleiben die Netzwerkverbindungen offen und keine neuen können erzeugt werden. Beim Browser sieht man, dass der Reload Button immer noch so aussieht als ob die Seite geladen ist und im Netzwerk-Tab sollte sowas sein?
![image](https://github.com/user-attachments/assets/c9808850-e36b-4f57-b898-d1834142339b)

**Comment by fb4thxUall** [comment]
Ja, wollte gerade schreiben, dass es nicht am Volume bzw den Pfaden liegen kann, denn das hatte ich vorher immer gelöscht und das war auch sichtbar, weil anschließend die DB auch immer leer/neu war.

Es erschließt sich mir aber auch mit deinem Input noch nicht, warum compose und manuelles run zu unterschiedlichen Ergebnissen führen, schließlich ist nach meinem Verständnis die Compose Datei nur eine Zusammenfassung der run Optionen, sodass man sich nicht jedesmal neu darum bemühen muss, sondern einfach die Startkonfiguration aus der Datei nehmen kann. Technisch passiert nach meinem Verständnis im Hintergrund aber das gleiche.

Ich bin allerdings selbst Docker Neuling und OpenLibry ist das erste Projekt, wo ich mit Docker arbeite. Ich halte Irrtümer meinerseits da für sehr wahrscheinlich.

Am 20. August 2024 08:37:54 MESZ schrieb Jure Zakotnik ***@***.***>:
>Ich kann den Fehler reproduzieren und denke kann es auch leicht lösen. Bei mir scheint es nur unter Docker so, als ob nach dem Import auf der Bücherseite der Browser versucht die Cover zu laden, diese sind nicht da und dann bleiben die Netzwerkverbindungen offen und keine neuen können erzeugt werden. Beim Browser sieht man, dass der Reload Button immer noch so aussieht als ob die Seite geladen ist und im Netzwerk-Tab sollte sowas sein?
>![image](https://github.com/user-attachments/assets/c9808850-e36b-4f57-b898-d1834142339b)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jzakotnik/openlibry/issues/131#issuecomment-2298078335
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jzakotnik** [comment]
Versuch mal für die Docker Compose Installation die `.env` Variable auf den lokalen Pfad im Volume zu setzen, d.h. `COVERIMAGE_FILESTORAGE_PATH=/app/public/coverimages`. Dann sollte es gehen.

**Comment by jzakotnik** [comment]
Fix damit ein falscher Pfad nicht alles lahm legt: [PR](https://github.com/jzakotnik/openlibry/pull/134)

**Comment by jzakotnik** [comment]
@fb4thxUall Hast Du auch eine Test vs Prod Installation? Dann würde ich Prod immer auf den Release Tag setzen und mit Main testen..

**Comment by fb4thxUall** [comment]
Ich teste alles in Kürze mal auf meiner Test-Installation. Komme aber heute nicht mehr dazu.

**Comment by fb4thxUall** [comment]
Hi, entschuldige für die absolut unangemessen endlose Wartezeit. Ich habe immer wieder versucht, mich dran zu setzen. Immer kam was Dringenderes dazwischen. Jetzt aber endlich will ich es mal als erledigt markieren :-)
