### ISSUE TITLE
Vorschlag: Neues Release

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#132]
Es hat sich ja doch einiges getan...
Jetzt wäre es nur verdient, wenn deine Software auch noch mehr Aufmerksamkeit bekäme. Wenn man es kennt, findet man es per Websuche. Wenn man aber sowas in die Suchmaschine eingibt "digitale bibliotheksverwaltung schule" nicht. Vielleicht lohnt es sich, die Webseite dahingehend zu optimieren.

**Comment by jzakotnik** [comment]
Neues Release veröffentlicht 💯 

Suchoptimierung ist eine gute Idee, aber habe auch nix dagegen, wenn es noch stabiler läuft 😄 

So sieht die Search Console aktuell aus:
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/f3b99c56-86b9-4c5e-9897-4e081522ad9b">
