### ISSUE TITLE
Anleitung zum Einbinden eines HTTPs-Zertifikats

### ISSUE THREAD

**Issue by jornfranke** [jzakotnik/openlibry#25]
Häufig erlauben Browser keine unverschlüsselten Verbindungen oder zeigen eine Warnung. Und Verschlüsselung ist immer wichtig (braucht man sowieso für: https://github.com/jzakotnik/openlibry/issues/15)
Evt. sollte man zum README.md hinzufügen.

[Let's encrypt](https://letsencrypt.org/de/docs/) vergibt kostenlose Zertifikate und hat auch eine Möglichkeit die automatisch auszutauschen - das heißt geringer Administrationsaufwand sobald es einmal aufgesetzt ist.

**Comment by jzakotnik** [comment]
Erste Anleitung für Setup mit nginx Proxy und certbot mit LetsEncrypt hier erzeugt: https://github.com/jzakotnik/openlibry/blob/main/doc/WebServerInstall.md

**Comment by jornfranke** [comment]
Ok - habe ich überlesen :)
